apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: nginx
    tier: frontend
spec:
  selector:
    matchLabels:
      app: myapp-nginx
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        app: myapp-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
