---
name: Custom variable
on:
    workflow_dispatch:
env:
    GLOBAL_VAR: "This is set as global veriable"
jobs:
    custom_variable:
        runs-on: [self-hosted, gh-runner]
        env:
            JOB_VAR: "This is set as job variable"
        steps:
            - name: Print default environment variable
              run: |
                echo "\$GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
                echo "\$GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
                echo "\$GITHUB_ACTION: $GITHUB_ACTION"
                echo "\$GITHUB_ACTOR: $GITHUB_ACTOR"
                echo "\$GITHUB_SHA: $GITHUB_SHA"
                echo "\$GITHUB_REF: $GITHUB_REF"
                echo "\$GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
                echo "\$GITHUB_BASE_REF: $GITHUB_BASE_REF"
                echo "\$GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
                echo "\$GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
                echo "\$GITHUB_SHA: $GITHUB_SHA"
                echo "\$GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
                echo "\$GITHUB_TOKEN: $GITHUB_TOKEN"
                echo "\$RUNNER_OS: $RUNNER_OS"
                echo "\$RUNNER_TOOL_CACHE: $RUNNER_TOOL_CACHE"
                echo "\$RUNNER_TEMP: $RUNNER_TEMP"
                echo "\$RUNNER_WORKSPACE: $RUNNER_WORKSPACE"
                echo "\$GITHUB: $GITHUB"
                echo "\$HOME: $HOME"
                echo "\$GITHUB_JOB: $GITHUB_JOB"
                echo "\$GITHUB_RUN_ID: $GITHUB_RUN_ID"
                echo "\$GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
                echo "\$GITHUB_RETENTION_DAYS: $GITHUB_RETENTION_DAYS"
                echo "\$GITHUB_SERVER_URL: $GITHUB_SERVER_URL"
                echo "\$GITHUB_API_URL: $GITHUB_API_URL"
                echo "\$GITHUB_GRAPHQL_URL: $GITHUB_GRAPHQL_URL"
                echo "\$RUNNER_NAME: $RUNNER_NAME"
                echo "\$RUNNER_ID: $RUNNER_ID"
                echo "\$RUNNER_GROUP: $RUNNER_GROUP"
                echo "\$RUNNER_USER: $RUNNER_USER"
                echo "\$RUNNER_REPO: $RUNNER_REPO"
                echo "\$RUNNER_WORKSPACE: $RUNNER_WORKSPACE"
                echo "\$RUNNER_OS: $RUNNER_OS"
                echo "\$RUNNER_ARCHITECTURE: $RUNNER_ARCHITECTURE"
                echo "\$RUNNER_IP_ADDRESS: $RUNNER_IP_ADDRESS"
                echo "\$RUNNER_LABELS: $RUNNER_LABELS"
                echo "\$RUNNER_VERSION: $RUNNER_VERSION"
                echo "\$RUNNER_DOWNLOAD_URL: $RUNNER_DOWNLOAD_URL"
                echo "\$RUNNER_TEMP: $RUNNER_TEMP"
                echo "\$RUNNER_TOOL_CACHE: $RUNNER_TOOL_CACHE"
                echo "\$RUNNER_TRACKING_ID: $RUNNER_TRACKING_ID"
                echo "\$RUNNER_DEBUG: $RUNNER_DEBUG"
                echo "\$RUNNER_ALLOW_RUNASROOT: $RUNNER_ALLOW_RUNASROOT"
                echo "\$RUNNER_TIMEOUT: $RUNNER_TIMEOUT"
                echo "\$RUNNER_IDLE_TIMEOUT: $RUNNER_IDLE_TIMEOUT"
                echo "\$RUNNER_SHUTDOWN_TIMEOUT: $RUNNER_SHUTDOWN_TIMEOUT"
                echo "\$RUNNER_WORKSPACE_CLEAN: $RUNNER_WORKSPACE_CLEAN"
                echo "\$RUNNER_WORKSPACE_REUSABLE: $RUNNER_WORKSPACE_REUSABLE"
                echo "\$RUNNER_WORKSPACE_DELETE: $RUNNER_WORKSPACE_DELETE"
                echo "\$RUNNER_REPLACE_EXISTING: $RUNNER_REPLACE_EXISTING"
                echo "\$RUNNER_DISABLE_MULTIARCH: $RUNNER_DISABLE_MULTIARCH"
                echo "\$RUNNER_DISABLE_ENTRYPOINT_OVERRIDE: $RUNNER_DISABLE_ENTRYPOINT_OVERRIDE"
                echo "\$RUNNER_LABELS: $RUNNER_LABELS"
                echo "\$RUNNER_CONFIG: $RUNNER_CONFIG"
                echo "\$RUNNER_CONFIG_PATH: $RUNNER_CONFIG_PATH"
                echo "\$RUNNER_SECRETS_PATH: $RUNNER_SECRETS_PATH"
                echo "\$RUNNER_CREDENTIALS_PATH: $RUNNER_CREDENTIALS_PATH"
                echo "\$RUNNER_SETTINGS_PATH: $RUNNER_SETTINGS_PATH"
            - name: Print global and job variable
              run: |
                echo "\$GLOBAL_VAR: $GLOBAL_VAR"
                echo "\$JOB_VAR: $JOB_VAR"
            - name: Set step variable
              env:
                  STEP_VAR: "This is set as step variable"
              run: |
                echo "\$GLOBAL_VAR: $GLOBAL_VAR"
                echo "\$JOB_VAR: $JOB_VAR"
                echo "\$STEP_VAR: $STEP_VAR"
                echo "STEP_VAR='This is new step variable" >> $GITHUB_ENV
            - name: Let me check whether I can access $STEP_VAR
              run: |
                echo "\$STEP_VAR: $STEP_VAR"
...