---
name: Sample for GITHUB_TOKEN
on:
    workflow_dispatch:
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
    sample_for_github_token:
        runs-on: [self-hosted, gh-runner]
        steps:
            - name: Print GITHUB_TOKEN
              run: |
                echo "\$GITHUB_TOKEN: $GITHUB_TOKEN"
            - name: Make API request
              run: |
                curl -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $GIHUB_TOKEN" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/OWNER/REPO
...