
---
name: This example of Schedule event
on:
    schedule:
    - cron: "15 8 * * *"
jobs:
    simple_schedule:
        name: Simple schedule
        runs-on: [self-hosted, u22-wsl, gh-runner]
        steps:
            - name: Print the schedule time
              run: |
                echo "This workflow schedule to run on ${{ github.event.schedule }}"

            
