---
name: This example of schedule and workflow_dispatch
on:
    schedule:
        - cron: '10 12 * * *'
    workflow_dispatch:
        inputs:
            name:
                description: 'Name of the person'
                required: true
                default: 'Kannan Vellaichamy'
                type: string
jobs:
    sample-job:
        runs-on: [self-hosted, u22-wsl, gh-runner]
        steps:
            - name: Print the name
              run: |
                date
                name='${{ inputs.name }}'
                if [ '${{ github.event.schedule }}' == '10 12 * * *' ]
                then
                    name='SriVelan'
                fi
                echo "Hello $name"
