name: Simple workflow

on:
    # push:
    #     branches:
    #         - main
    workflow_dispatch:
        inputs:
            image_list:
                description: Image list
                type: string
                required: false
env:
    test: "kannan"
    image_list: ${{ inputs.image_list }}
jobs:
    simple_workflow:
        runs-on: [self-hosted, gh-runner]
        steps:
            - name: Print input vars
              run: |
                echo gh_input:${{ inputs.image_list }}
                echo env:$image_list

    # sleep_job:
    #     runs-on: [self-hosted, gh-runner]
    #     needs: simple_workflow
    #     steps:
    #         - name: Sleep for 5 secs
    #           run: |
    #             sleep 5
    #             date
    # simple_workflow:
    #     runs-on: [self-hosted, gh-runner]
    #     steps:
    #         - name: Just print message
    #           run: |
    #             echo "\$skip_step_one: $skip_step_one"
    #             echo "\$test: ${test}"
    #             if [ ${test} == "kannan" ]
    #             then
    #                 echo "Success and exiting..."
    #                 exit
    #             fi
    #             echo "This is after the condition"
    #         - name: This is after step1
    #           run: |

    #             if [ $skip_step_one == "true" ]
    #             then
    #                 exit
    #             fi
    #             echo "Hello World!"
