name: Simple workflow

on:
    # push:
    #     branches:
    #         - main
    workflow_dispatch:
        inputs:
            skip_step_one:
                description: Do you want to skip step1?
                type: boolean
                required: true
                default: false
env:
    test: "kannan"
    skip_step_one: ${{ inputs.skip_step_one }}
jobs:
    # sleep_job:
    #     runs-on: [self-hosted, gh-runner]
    #     needs: simple_workflow
    #     steps:
    #         - name: Sleep for 5 secs
    #           run: |
    #             sleep 5
    #             date
    simple_workflow:
        runs-on: [self-hosted, gh-runner]
        steps:
            - name: Just print message
              run: |
                echo "\$skip_step_one: $skip_step_one"
                echo "\$test: ${test}"
                if [ ${test} == "kannan" ]
                then
                    echo "Success and exiting..."
                    exit
                fi
                echo "This is after the condition"
            - name: This is after step1
              run: |

                if [ $skip_step_one == "true" ]
                then
                    exit
                fi
                echo "Hello World!"
