---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrapp-deployment
  labels:
    app: hrapp
    type: front-end
spec:
  template:
    metadata:
      name: hrapp-pod
      labels:
        app: hrapp
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.26
  replicas: 3
  selector:
    matchLabels:
      type: front-end
...