---
apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: hrapp-rs
  labels:
    app: hrapp
    type: front-end
spec:
  template:
    metadata:
      name: hrapp-pod
      labels:
        app: hrapp
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end
...