---
apiVersion: v1
kind: Service
metadata:
  name: nginx-hrapp
  labels:
    app: hrapp
    type: front-end
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    app: hrapp
    type: front-end
...
      